### ISSUE TITLE
config.yml false is interpreted as true

### ISSUE THREAD

**Issue by mbalandis** [dnomd343/syncplay-docker#1]
`/etc/syncplay/config.yml` when written it reads Booleans as flags so if you set it is becomes `true` regardless. Took me a good hour to figure out why chat is disabled even if I set to: `disable-chat: false`. So it needs to be omitted unless you want the value to be `true`.

Not a big deal but can be confusing as it is not properly read in code.

Below will be persistent, enabled stats and tls even if I set it to false and disable-chat will be disabled if I uncomment it. Strings work fine.

```yml
salt: '?8oyRLMHWTgt'
random-salt: true
password: '1234567'
persistent: true 
enable-stats: true
enable-tls: true
# disable-chat: false
```
